version: 2.1

workflows:
  workflow:
    jobs:
      - linux-test:
          name: PHP 8.1
          docker-image: cimg/php:8.1
      - linux-test:
          name: PHP 8.2
          docker-image: cimg/php:8.2

jobs:
  linux-test:
    parameters:
      docker-image:
        type: string

    docker:
      - image: <<parameters.docker-image>>

    steps:
      - checkout
      - run:
          name: install dependencies
          command: composer install --no-progress
      - run: mkdir -p ./phpunit
      - run:
          name: run tests
          command: php vendor/bin/phpunit
      - store_test_results:
          path: ./phpunit
      - store_artifacts:
          path: ./phpunit
