name: Run CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  linux-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.1, 8.2]
        use-lowest-dependencies: [true, false]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # If you only need the current version keep this.

      - uses: ./.github/actions/ci
        with:
          php-version: ${{ matrix.php-version }}
          use-lowest-dependencies: ${{ matrix.use-lowest-dependencies }}
          token: ${{ secrets.GITHUB_TOKEN }}
